config/routes.rb
TwitterClone::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, only: :show
  resources :tweets
  resources :relationships, only: [:create, :destroy]
  root to: 'users#index'

end

app/models/controller.rb
class Controller < ActiveRecord::Base
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates :content, :presence => true, :length => { :maximum => 140}

  def mention_mail
    self.content.split(' ').each do |word|
      if self.usernames.include?(word[1..-1])
        handle = word[1..-1]
        if !User.find_by(:handle => handle).nil?
          user = User.find_by(:handle => handle)
          UserMailer.tweet_mailer(user, self).deliver
        end
      end
    end
  end

  def usernames
    if /@([A-Za-z0-9_]{1,15})/.match(self.content)
      self.content.scan(/@([A-Za-z0-9_]{1,15})/).flatten
    else
      return ""
    end
  end

  def print_tweet
    string =''
    self.content.split(' ').each do |word|
      if self.usernames.include?(word[1..-1])
        handle = word[1..-1]
        if !User.find_by(:handle => handle).nil?
          string+= '<a href="/users/' + User.find_by(:handle => handle).id.to_s + '"> ' +word+ ' </a>'
        else
          string += word + " "
        end
      else
        string += word + " "
      end
    end
    string
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
  has_many :relationships
  has_many :followed_users
  has_many :followed_users, through: :relationships, source: :followed_id
  validates_presence_of :handle

  before_create :welcome_message

  def welcome_message
    UserMailer.welcome_message(self).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :handle
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    super

  end

  def update
    super
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:id])
    @user.followers << current_user
    redirect_to :back
  end


end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController




end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      current_user.tweets << @tweet
      @tweet.mention_mail
      redirect_to :back, notice: "Tweet Created."
    else
      redirect_to user_path(current_user), :flash => { :error => "BAD TWEET!" }
    end
  end

private
  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if current_user
      redirect_to user_path(current_user)
    end
  end

  def show
    @tweet = Tweet.new
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix the following errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Home</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Active</a></li>
      <% if current_user %>
      <li><%= link_to current_user.handle, user_path(current_user) %></li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if !current_user %>
        <li><%= link_to "sign up", new_user_registration_path %></li>
        <li><%= link_to "sign in", new_user_session_path %></li>
      <% else %>
        <li><%= link_to "sign out", destroy_user_session_path, :method => :delete  %></li>
      <% end %>


    </ul>
  </div>
</div>
  <div class='container'>
<%= flash[:notice] %>
<%= flash[:error] %>
<%= yield %>

</div>
</body>
</html>

app/views/users/show.html.erb
<h3><%= @user.handle %>'s Page</h3>

<% if current_user != @user %>
  <%= link_to "Follow", relationships_path(:params => {:id => @user.id}), :method => :post, :class => 'btn btn-primary' %>
<% end %>

<% if current_user == @user %>
  <%= form_for @tweet do |t| %>
    <%= t.label :content, "TWEET" %>
  </br>
    <%= t.text_field :content %>
  </br>
    <%= t.submit %>
  <% end %>
<% end %>

<%= render "layouts/errors", :object => @tweet %>
<ul>
  <% @user.tweets.each do |t| %>
   <li> <%= t.print_tweet.html_safe %> | tweeted <%= time_ago_in_words(t.created_at) %> ago.</li>
  <% end %>
</ul>